#!/usr/bin/env bash
PROGRAM_NAME=$(basename "$0")
# shellcheck disable=SC2124
BBOXES="${@}"
BBOXES="${BBOXES:--}" # split string based on regex https://stackoverflow.com/a/45025569

function usage {
    echo "Convert bounding box to WKT object"
    echo ""
    echo "usage: $PROGRAM_NAME <bbox>"
    echo "    arguments:"
    echo "        - <bbox>: \$minx,\$miny,\$maxx,\$maxy in EPSG:4326 (arg or stdin)"
    exit 1
}

set -euo pipefail

function process_bbox(){
    local input_string
    local array
    local minx
    local maxx
    local miny
    local maxy
    input_string=$1
    if [[ -z $input_string ]];then
        return
    fi
    input_string=${input_string// /}
    IFS=',' read -r -a array <<< "$input_string"
    minx=${array[0]}
    miny=${array[1]}
    maxx=${array[2]}
    maxy=${array[3]}
    echo "POLYGON(($minx $miny,$minx $maxy,$maxx $maxy,$maxx $miny,$minx $miny))"
}

if [[ $BBOXES == "-" ]];then
# BBOX passed on stdin
    if [ -t 0 ]; then
    # if do not allow interactive tty
        usage
        exit 1
    fi
    while read -r line
    do  
        process_bbox "$line"
    done < "/dev/stdin"
else
# BBOX passed as argument
    IFS=$'\n'
    # shellcheck disable=2013
    for BBOX in $(grep --perl-regexp --only-matching '((-?\d*\.?\d*)\s?,\s?(-?\d*\.?\d*)\s?,\s?(-?\d*\.?\d*)\s?,\s?(-?\d*\.?\d*))\s?'  <<<"$BBOXES");do
        BBOX="${BBOX//[[:space:]]/}"
        process_bbox "$BBOX"
    done
fi
