#!/usr/bin/env bash
PROGRAM_NAME=$(basename "$0")
EPSG_IN=$1
EPSG_OUT=$2
X=$3
Y=$4

function usage {
    echo "Reproject coordinate. Requires cs2cs binary from the Proj library."
    echo ""
    echo "usage: $PROGRAM_NAME <input_epsg_code> <output_epsg_code> <X> <Y>"
    exit 1
}

if test "$#" -ne 4; then
    usage

fi
set -euo pipefail
echo "$X" "$Y" | cs2cs -f "%.6f" "+init=epsg:${EPSG_IN}" +to "+init=epsg:${EPSG_OUT}"
